[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dao_program = "HPH6itf3pTzFGReDBju8XhvQ8kgN1Wtpmd4oqXgaXKqp"

[programs.localnet]
dao_program = "Aov7JqVe1igEQEYR7pKD4surZ6wLfb2uNmNurPxo1u9q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/caseycharlesworth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
